version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker: 
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache: 
          paths: 
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm start
workflows:
    build-and-test:
      jobs:
        - build