version: 2
jobs:
  build:
    working_directory: ~/Source/super-awesome
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: 
          name: Test the App
          command: npm test -- --progress=false --browsers=ChromeNoSandbox
      - run:
          name: Run E2E Tests
          command: node_modules/.bin/webdriver-manager update
          command: npm run e2e -- --protractor-config=protractor-ci.conf.js 
      - run: 
          name: Serve the App
          command: npm start &
      - run: echo You are super awesome!