version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
      - run: use npm 14.4.0
      - run: npm build
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
      - run: use npm 14.4.0
      - run: npm test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
