version: 2.1

jobs:
  build:
    docker: 
      - image: circleci/node:8-browsers
    working_directory: ~/Source/super-awesome
    steps:
      - checkout
      - restore_cache: 
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - save_cache: 
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: ng build --prod
      - run: ng test --single-run