version: 2
jobs:
  build:
    working_directory: ~/Source/super-awesome
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm test -- --single-run --no-progress --browser=ChromeNoSandbox
      - run: npm e2e -- --no-progress --config=protractor-ci.conf.js